#!/bin/sh
lock() {
    i3lock -c 073642 -i ~/Pictures/wallpaper.png -t -e -f
}

log_event "Initialized $1"
case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac
log_event "Finished $1"

exit 0
