#!python
import argparse
import pathlib
import re

from collections import Counter

DELIMITERS=r",;\t"
REGEX=re.compile(r"(?P<word>(?P<q>[\"'])([^\1]*)(?P=q)|[^"+DELIMITERS+r"\n]*)(?P<separator>["+DELIMITERS+r"])?")

parser = argparse.ArgumentParser(description='Auto-detect delimiters in CSV')
parser.add_argument(
    "file", type=pathlib.Path, help="CSV file"
)
args = parser.parse_args()

with open(args.file) as f:
    head = [next(f) for _ in range(2)]

line_matches = [re.finditer(REGEX, line) for line in head]
separators = []
for matches in line_matches:
    separators.append(Counter(filter(None, (m.groupdict()["separator"] for m in matches))))

determinant = Counter()
for index, sep in enumerate(separators):
    for other in separators[index+1:]:
        diff = {k: abs(other.get(k, 0) - v) for k, v in sep.items()}
        determinant.update(diff)

print(determinant.most_common()[-1][0])
if not head:
    exit(-1)

